version: "3.4"
          
services:
  pythonapp:
    container_name: bank-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:5000
    networks:
      app-network:
        ipv4_address: 172.25.0.10

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: Dockerfile.nginx   
    depends_on:
      - pythonapp
    networks:
      app-network:
        ipv4_address: 172.25.0.11
    volumes:
      - /home/bank/git/logs:/var/log/nginx


networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1





