FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/certs

COPY ./nginx/nginx.conf /etc/nginx/

COPY ./nginx/nginx.template.conf /etc/nginx/conf.d

COPY ./nginx/entrypoint.sh /

RUN chmod +x /entrypoint.sh

CMD ["/entrypoint.sh"]

