FROM nginx

RUN rm /etc/nginx/conf.d/default.conf

RUN mkdir -p /etc/nginx/certs

COPY ./nginx/nginx.conf /etc/nginx/

COPY ./nginx/nginx-cert.conf /etc/nginx/conf.d

ENTRYPOINT ["nginx", "-g", "daemon off;"]

