FROM python:3.9

ARG PG_UID=1002
ARG PG_GID=1003

RUN apt-get update && apt-get install -y libpq-dev
RUN pip install psycopg2

RUN mkdir -p /app/data
COPY ./check_and_create_DB.py /app/check_and_create_DB.py 

RUN chmod a+x /app/check_and_create_DB.py
RUN touch /app/data/errors_DB.yml && chmod a+rw /app/data/errors_DB.yml

CMD ["python", "/app/check_and_create_DB.py"]
