FROM python:3.9

ARG PG_UID=1002
ARG PG_GID=1003

RUN apt-get update\
    && apt-get install -y libpq-dev \
    && pip install psycopg2

RUN mkdir -p /apps/data
COPY ./check_and_create_DB.py /apps/check_and_create_DB.py

RUN chmod a+x /apps/check_and_create_DB.py \
    && touch /apps/data/errors_DB.yml \
    && chmod a+rw /apps/data/errors_DB.yml 

CMD ["bash", "-c", "sleep 20 && python /apps/check_and_create_DB.py"]
