version: "3.4"
          
services:
  pythonapp:
    container_name: bank-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      - app-network
                
  nginx-cert:
    container_name: nginx-cert
    networks:
      - app-network   
    build:
      context: .
      dockerfile: Dockerfile.nginx-cert
    ports: 
      - 80:80
    depends_on:
      - certbot
        
  nginx-app:
    container_name: nginx-app
    build:
      context: .
      dockerfile: Dockerfile.nginx   
    networks:
      - app-network                    
    ports: 
      - 443:443
    volumes:
      - ./logs:/var/log/nginx
      - ./certs:/etc/letsencrypt:rw
    depends_on:
      certbot:
        condition: service_completed_successfully    
  
  certbot:
    container_name: certbot
    build:
      context: .
      dockerfile: Dockerfile.certbot
    networks:
      app-network:
        ipv4_address: 172.25.0.10
    volumes:
      - ./certs:/etc/letsencrypt:rw
         
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: Dockerfile.postgres
      args:
        CRYPT_PASSWORD: "${CRYPT_PASSWORD}"
    environment:
      CRYPT_PASSWORD: "${CRYPT_PASSWORD}"   
    volumes:
      - ./pg_data1:/var/lib/postgresql/data
      - shared_volume:/app
    networks:
      - app-network
    ports:
      - 5432:5432
  
  script:
    container_name: db_script
    build:
      context: .
      dockerfile: Dockerfile.script
    networks:
      - app-network  
    volumes:
      - ./errors:/app/data
      - shared_volume:/app
      
              
networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1

volumes:
  shared_volume:
