version: "3.4"

services:
  pythonapp:
    build:
      context: .
      dockerfile: Dockerfile
      privileged: true
      ports:
        - "80:5000"
    
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
    depends_on:
      - pythonapp





