FROM postgres:15-bullseye

COPY ./secrets_decrypted.yml /

ENV PGDATA=/var/lib/postgresql/data/pgdata

ENV POSTGRES_PASSWORD_FILE=/secrets_decrypted.yml

CMD ["sh", "-c", "psql -U postgres -c \"CREATE DATABASE omegabank;\" --set=POSTGRES_PASSWORD=$(cat \"$POSTGRES_PASSWORD_FILE\")"]
