version: "3.4"
          
services:
  pythonapp:
<<<<<<< HEAD
    container_name: bank-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    networks:
      app-network:
        ipv4_address: 172.25.0.10

  nginx:
    container_name: nginx
    build:
      context: .
      dockerfile: ./nginx/Dockerfile.nginx   
    depends_on:
      - pythonapp
    networks:
      app-network:
        ipv4_address: 172.25.0.11
    volumes:
      - ./logs:/var/log/nginx
    ports: 
      - 80:80


networks:
  app-network:
    ipam:
      driver: default
      config:
        - subnet: 172.25.0.0/16
          gateway: 172.25.0.1



=======
    image: pythonapp:v0.2.0
    privileged: true
    ports:
      - "80:5000"
   
>>>>>>> develop


