version: "3.4"

services:
  pythonapp:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - 5000
    volumes:
      - CDdata:/home/bank/git

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    
    depends_on:
      - pythonapp

volumes:
  CDdata:



