- name: Main of all
  hosts: all
  vars_prompt:
    - name: "username"
      prompt: "enter username"
      private: no
      
    - name: "crypt_password"
      prompt: "Enter vault password"
      private: yes
  become: true  
  environment:
    ANSIBLE_VAULT_PASSWORD: "{{ crypt_password }}"    
    
  roles:
    - role: bank
    - role: git
    - role: clone repo
    - role: docker
    - role: postgres
    - role: docker-compose
