- name: Create 'bank' user and add to 'root' group
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
    state: present
    shell: /bin/bash
    home: /home/{{ username }}
    
- name: Add user to sudoers file
  lineinfile:
    dest: /etc/sudoers
    line: '{{ username }} ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'    


    


    

