- name: Create 'bank' user and add to 'root' group
  user:
    name: bank
    groups: root
    state: present
    shell: /bin/bash
    home: /home/bank

- name: Add user to sudoers file
  lineinfile:
    dest: /etc/sudoers
    line: 'bank ALL=(ALL:ALL) ALL'
    validate: 'visudo -cf %s'    



    

