- name: Change ownership of /home/{{ username }}/git directory
  file:
    path: /home/{{ username }}/git
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Clone repository
  become_user: "{{ username }}"
  git:
    repo: https://github.com/OpsStrike/dos14-Labzeev_Timofey-git-flow.git
    dest: /home/{{ username }}/git
    version: feature-hw-26
    force: yes
  changed_when: false
  
- name: Create logs Dir
  file:
    path: /home/bank/git/logs
    state: directory
    mode: '0777'


    

