- name: Change ownership of /home/{{ username }}/git directory
  file:
    path: /home/{{ username }}/git
    owner: "{{ username }}"
    group: "{{ username }}"
    recurse: yes

- name: Clone repository
  become_user: "{{ username }}"
  git:
    repo: https://github.com/OpsStrike/dos14-Labzeev_Timofey-git-flow.git
    dest: /home/{{ username }}/git
    version: feature-hw-29
    force: yes
  register: git_clone_result
  changed_when: "git_clone_result.stdout"

- name: Record the clone date and time
  set_fact:
    clone_updated: "{{ ansible_date_time.iso8601 }}"
  when: git_clone_result.changed

- name: Create logs Dir
  file:
    path: ./logs
    state: directory
    mode: '0777'
    
- name: Create certs Dir
  file:
    path: ./certs
    state: directory
    mode: '0777'
