- name: Установить pip
  apt:
    name: python3-pip  
    state: present
    update_cache: yes 

- name: Install Docker Compose for ansible
  become: true
  become_user: "{{ username }}"
  pip:
    name: docker-compose
    state: present

- name: Check for changes in the repository
  find:
    paths: /home/{{ username }}/git
    age: "{{ ansible_date_time.timedelta(minutes=-5) }}" 
    recurse: yes
  register: changed_files

- name: Rebuild Docker images
  command:
    cmd: docker-compose -f /home/bank/git/docker-compose.yaml build --build-arg CRYPT_PASSWORD="{{ CRYPT_PASSWORD }}"
  args:
    chdir: /home/bank/git
  when: changed_files.files | length > 0 

- name: Run Docker Compose
  become: true
  block:
    - name: Execute Docker Compose
      command:
        cmd: docker-compose -f /home/bank/git/docker-compose.yaml up -d postgres script
        chdir: /home/bank/git
