- name: install pip
  become: true
  apt: 
    name: python3-pip
    state: present
    update_cache: yes
    
- name: Install Docker Compose for ansible
  become: true
  become_user: "{{ username }}"
  pip:
    name: docker-compose
    state: present

- name: Run Docker Compose
  become: true
  block:
    - name: Execute Docker Compose
      command:
        cmd: docker-compose -f /home/bank/git/docker-compose.yaml up -d
        chdir: /home/bank/git
        
- name: chmod certs
  become: true
  file: 
    path: home/{{ username }}/certs
    mode: "0777"
      







  


