- name: Install Docker Compose for ansible
  become: true
  become_user: "{{ username }}"
  pip:
    name: docker-compose
    state: present

- name: Run Docker Compose
  become: true
  block:
    - name: Execute Docker Compose
      command:
        cmd: docker-compose -f /home/bank/git/docker-compose.yaml up -d postgres
        chdir: /home/bank/git

- name: Permissions for execute script
  file:
    path: /home/{{ username }}/git/check_and_create_DB.py
    mode: a+x

- name: Wait for PostgreSQL to start
  wait_for:
    host: postgres
    port: 5432
    state: started
    timeout: 10
        
- name: Check and create DB and tables
  command: python3 check_and_create_DB.py
  args:
    chdir: /home/{{ username }}/git/

      







  


