- name: Build Docker image
  become: true
  become_user: "{{ username }}"
  command: docker build -t pythonapp:v0.2.0 /home/{{ username }}/git
   
- name: Run Docker Compose
  become: true
  docker_compose:
    project_src: /home/{{ username }}/git/docker-compose.yaml
    state: started

  


