- name: Generate private key
  command: openssl genpkey -algorithm RSA -out "{{ ansible_env.PWD }}/.certs/private.key"

    
- name: Generate CSR
  expect:
    command: openssl req -new -key "{{ ansible_env.PWD }}/.certs/private.key" -out bank.csr
    responses:
      'Country Name .*': 'BY'
      'State or Province Name .*': 'Minsk'
      'Locality Name .*': 'Minsk'
      'Organization Name .*': 'omegabank'
      'Organizational Unit Name .*': ''
      'Common Name .*': 'tla.bank.smodata.net'
      'Email Address .*': '' 
      'Challenge Password .*': ''  
      'Optional Company Name .*': '' 

