- name: Generate private key
  command: openssl genpkey -algorithm RSA -out "{{ ansible_env.PWD }}/certs/private.key"

    

    
- name: Generate an OpenSSL Certificate Signing Request with Subject information
  community.crypto.openssl_csr:
    path: ./certs/bank.csr
    privatekey_path: ./certs/private.key
    country_name: BY
    organization_name: omegabank
    email_address: timosha9911@gmail.com
    common_name: tla.bank.smodata.net

