- name: install pip
  become: true
  apt: 
    name: python3-pip
    state: present
    update_cache: yes
    
- name: Install Git
  become: true
  apt:
    name: git
    state: present

- name: Install pyenv dependencies
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - make
    - build-essential
    - libssl-dev
    - zlib1g-dev
    - libbz2-dev
    - libreadline-dev
    - libsqlite3-dev
    - wget
    - curl
    - llvm
    - libncurses5-dev
    - xz-utils
    - tk-dev
    - libxml2-dev
    - libxmlsec1-dev
    - libffi-dev
    - liblzma-dev

- name: Add pyenv path to PATH
  become_user: "{{ username }}"
  blockinfile:
    dest: /home/{{ username }}/.bashrc
    block: |
      export PYENV_ROOT="$HOME/.pyenv"
      export PATH="$PYENV_ROOT/bin:$PATH"
      eval "$(pyenv init --path)"
    state: present
    
- name: Clone the Pyenv repository
  become_user: "{{ username }}"
  git:
    repo: https://github.com/pyenv/pyenv.git
    dest: /home/{{ username }}/.pyenv
    update: yes

- name: Установка Python 3.11.3 с помощью pyenv
  become_user: "{{ username }}"
  shell: |
    export PYENV_ROOT="$HOME/.pyenv"
    export PATH="$PYENV_ROOT/bin:$PATH"
    eval "$(pyenv init --path)"

    if [[ "$(pyenv versions | grep -q 3.11.3; echo $?)" != "0" ]]; then
        /home/{{ username }}/.pyenv/bin/pyenv install 3.11.3
    fi
    
    pyenv global 3.11.3
    pip3 install poetry
  args:
    executable: /bin/bash
  changed_when: false

- name: Проверка установленной глобальной версии Python
  become_user: "{{ username }}"
  stat:
    path: /home/{{ username }}/.pyenv/version
  register: pyenv_global_version

- name: True Global
  become_user: "{{ username }}"
  debug:
    msg: "OK"
  when: pyenv_global_version.stat.exists == True
  tags:
    - always
