- name: Install Ansible
  become: true
  apt:
    name: ansible
    update_cache: yes
    state: present

- name: Include .env file
  ansible.builtin.include_vars:
    file: .env

- name: Decrypt secrets.yml
  ansible.builtin.command: ansible-vault decrypt /home/{{ username }}/git/secrets.yml
  environment:
    ANSIBLE_VAULT_PASSWORD: "{{ ANSIBLE_VAULT_PASSWORD }}"

- name: update cache
  apt:
    update_cache: yes

- name: install PostgreSQL client
  apt:
   name: postgresql-client
   state: present
