- name: Install Ansible
  become: true
  apt:
    name: ansible
    update_cache: yes
    state: present

- name: install PostgreSQL client
  apt:
    name: postgresql-client
    state: present
    update_cache: yes



- name: install pip
  become: true
  apt: 
    name: python3-pip
    state: present
    update_cache: yes
    

- name: Установка libpq-dev
  become: yes
  apt:
    name: libpq-dev
    state: present
    update_cache: yes
    force: yes
    
- name: Install psycopg2
  pip:
    name: psycopg2
    state: present

