- name: Install Ansible
  become: true
  apt:
    name: ansible
    update_cache: yes
    state: present

- name: Decrypt secrets.yml
  ansible.builtin.command: ansible-vault decrypt /home/{{ username }}/git/secrets.yml

- name: update cache
  apt:
    update_cache: yes

- name: install PostgreSQL client
  apt:
   name: postgresql-client
   state: present
