- name: Install Ansible
  become: true
  apt:
    name: ansible
    update_cache: yes
    state: present

- name: update cache
  apt:
    update_cache: yes

- name: install PostgreSQL client
  apt:
    name: postgresql-client
    state: present

- name: create secrets_decrypted.yml   
  file:
    path: /home/{{ username }}/git/secrets_decrypted.yml
    state: touch
    
- name: Decrypt secrets.yml 
  ansible.builtin.expect:
    command: ansible-vault decrypt /home/{{ username }}/git/secrets.yml --output /home/{{ username }}/git/pass/secrets_decrypted.yml
    responses:
      Vault password: "{{ ansible_password }}"

- name: Set permissions for secrets_decrypted.yml
  file:
    path: /home/{{ username }}/git/secrets_decrypted.yml
    mode: '0777'
    state: file
